apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - server-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: structured-log
    includeSelectors: false
