name: structured_log_material_example
description: "structured_log_material example app (web)."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  structured_log: ^0.2.0-dev.0+1
  structured_log_flutter:
    path: ../../structured_log_flutter
  structured_log_material:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
